export default {
    "SendBouncesNotifications": false,
    "SendOpensNotifications": false,
    "SendClicksNotifications": false,
    "SendInboundNotifications": false,
    "SendDeliveredNotifications": false,
    "SendViolationsNotifications": false,
    "SendBouncesToSender": false,
    "BouncesFromEmailAddress": "pmnotifications+bounces@yourdomain.com",
    "OpensFromEmailAddress": "pmnotifications+opens@yourdomain.com",
    "ClicksFromEmailAddress": "pmnotifications+opens@yourdomain.com",
    "InboundFromEmailAddress": "pmnotifications+inbound@yourdomain.com",
    "DeliveredFromEmailAddress": "pmnotifications+delivered@yourdomain.com",
    "OpensToEmailAddress": "email@yourdomain.com",
    "ClicksToEmailAddress": "email@yourdomain.com",
    "InboundToEmailAddress": "email@yourdomain.com",
    "BouncesToEmailAddress": "email@yourdomain.com",
    "DeliveredToEmailAddress": "email@yourdomain.com",
    "ViolationsFromEmailAddress": "pmnotifications+violations@yourdomain.com",
    "ViolationsToEmailAddress": "email@yourdomain.com"
  }
